BEGIN TRANSACTION;

CREATE TABLE word(word_id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR);
CREATE TABLE word_count(word_count_id INTEGER PRIMARY KEY AUTOINCREMENT, word_id INTEGER, count INTEGER, FOREIGN KEY(word_id) REFERENCES word(word_id));

COMMIT;
